name: Deploy HTML Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: List files
      run: |
        ls -la
        echo "Site is ready!"
    
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: .
